algoritmo "somar"
// Função :  Soma de dois valores
// Autor : Melissa Perdomo
// Data : 30/08/2024
// Seção de Declarações 
var
   numeroA, numeroB, resultado: inteiro
inicio
      escreval ("Bora fazer uma soma?")
      escreval
      escreval ("Digite o primeiro valor:")
      leia (numeroA)
      escreval ("Digite o segundo valor:")
      leia (numeroB)
      resultado <- numeroA + numeroB
      escreval
      escreval ("O resultado é:")
      escreva (resultado)
fimalgoritmo
